name: Node.js CI/CD Pipeline

# Kích hoạt workflow khi có code push lên nhánh main hoặc tmtayato
on:
  push:
    branches: [ "main", "tmtayato" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Chạy trên môi trường ảo Ubuntu

    steps:
    - name: Lấy code từ repo
      uses: actions/checkout@v4

    - name: Cài đặt Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # Bạn có thể đổi sang 20 nếu máy bạn đang dùng bản 20

    - name: Cài đặt các thư viện (Dependencies)
      run: npm install

    - name: Chạy Unit Test với Jest
      run: npm test